vich_uploader:
    db_driver: orm

    mappings:
        module_image:
            uri_prefix: /images/modules
            upload_destination: '%kernel.project_dir%/public/images/modules'
            namer: Vich\UploaderBundle\Naming\UniqidNamer
