version: "3"

services:
    php:
        container_name: 29ter-apache-symfony
        image: 29ter/apache-symfony
        ports:
            - "81:80"
        volumes:
            - .:/var/www/html:cached
        links:
            - mysql
    
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        links:
            - mysql
        environment:
            PMA_HOST: mysql
            PMA_PORT: 3306
        ports:
            - '8080:80'

    mysql:
        image: mariadb:10.3
        container_name: bdd
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: database
            MYSQL_USER: admin
            MYSQL_PASSWORD: admin
        ports:
            - "3306:3306"